name: AoC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: gradle
      - name: Run tests
        run: ./gradlew test --no-daemon

      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 2211108
          session: ${{ secrets.AOC_SESSION }}
          year: 2022

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update badges
